In [1]:
%pip install numpy
%pip install pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (1.21.0)
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/3.0.16_1/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /usr/local/Cellar/jupyterlab/3.0.16_1/libexec/lib/python3.9/site-packages (1.3.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/Cellar/jupyterlab/3.0.16_1/libexec/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/site-packages (from pandas) (1.21.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/Cellar/jupyterlab/3.0.16_1/libexec/lib/python3.9/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/Cellar/jupyterlab/3.0.16_1/libexec/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/3.0.16_1/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [3]:
stlcity_91_05 = pd.read_csv("stlcity_91_05.csv")
stlcity_06_20 = pd.read_csv("stlcity_06_20.csv")

In [4]:
stlcity_91_05.head()

,YEAR,COUNTY_DISTRICT_CODE,DISTRICT_NAME,SCHOOL_CODE,SCHOOL_NAME,TITLE1_FLAG,TITLE1_FLAG_DESC,ENROLLMENT_GRADES_K_12,JANUARY_MEMBERSHIP,LUNCH_COUNT_FREE_REDUCED,...,ENROLLMENT_PACIFIC_ISLANDER,ENROLLMENT_PACIFIC_ISLANDER_PCT,ENROLLMENT_WHITE,ENROLLMENT_WHITE_PCT,ENROLLMENT_ELL_LEP,ENROLLMENT_ELL_LEP_PCT,ENROLLMENT_GRADE_PK_ELL_LEP,ENROLLMENT_GRADE_PK_ELL_LEP_PCT,IEP_SCHOOLAGE_CHILDCOUNT,IEP_INCIDENCE_RATE
0,1995,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,105,72,*,...,NaN,NaN,6,5.71,*,*,*,*,*,*
1,1996,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,94,73,35,...,NaN,NaN,*,*,*,*,*,*,*,*
2,1997,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,88,70,43,...,NaN,NaN,5,5.68,*,*,*,*,*,*
3,1998,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,82,78,35,...,NaN,NaN,5,6.1,*,*,*,*,*,*
4,1999,115115,ST LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,70,39,15,...,NaN,NaN,*,*,*,*,*,*,*,*

In [6]:
stlcity_00_05 = stlcity_91_05[stlcity_91_05["YEAR"] >= 2000]

In [7]:
stlcity_00_05.head()

,YEAR,COUNTY_DISTRICT_CODE,DISTRICT_NAME,SCHOOL_CODE,SCHOOL_NAME,TITLE1_FLAG,TITLE1_FLAG_DESC,ENROLLMENT_GRADES_K_12,JANUARY_MEMBERSHIP,LUNCH_COUNT_FREE_REDUCED,...,ENROLLMENT_PACIFIC_ISLANDER,ENROLLMENT_PACIFIC_ISLANDER_PCT,ENROLLMENT_WHITE,ENROLLMENT_WHITE_PCT,ENROLLMENT_ELL_LEP,ENROLLMENT_ELL_LEP_PCT,ENROLLMENT_GRADE_PK_ELL_LEP,ENROLLMENT_GRADE_PK_ELL_LEP_PCT,IEP_SCHOOLAGE_CHILDCOUNT,IEP_INCIDENCE_RATE
5,2000,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,71,69,32,...,NaN,NaN,5,7.04,*,*,*,*,*,*
6,2001,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,86,81,43,...,NaN,NaN,11,12.79,*,*,*,*,*,*
7,2002,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,92,82,35,...,NaN,NaN,*,*,*,*,*,*,*,*
8,2003,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,73,89,43,...,NaN,NaN,*,*,*,*,*,*,*,*
9,2004,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,98,98,45,...,NaN,NaN,5,5.1,*,*,*,*,*,*

In [8]:
stlcity_91_05.shape

(1732, 33)

In [9]:
stlcity_00_05.shape

(695, 33)

In [10]:
stlcity_06_20.shape

(1622, 33)

In [12]:
stlcity_00_20 = pd.concat([stlcity_00_05, stlcity_06_20], ignore_index=True)

In [13]:
stlcity_00_20.shape

(2317, 34)

In [15]:
stlcity_00_20.head(20)

,YEAR,COUNTY_DISTRICT_CODE,DISTRICT_NAME,SCHOOL_CODE,SCHOOL_NAME,TITLE1_FLAG,TITLE1_FLAG_DESC,ENROLLMENT_GRADES_K_12,JANUARY_MEMBERSHIP,LUNCH_COUNT_FREE_REDUCED,...,ENROLLMENT_PACIFIC_ISLANDER_PCT,ENROLLMENT_WHITE,ENROLLMENT_WHITE_PCT,ENROLLMENT_ELL_LEP,ENROLLMENT_ELL_LEP_PCT,ENROLLMENT_GRADE_PK_ELL_LEP,ENROLLMENT_GRADE_PK_ELL_LEP_PCT,IEP_SCHOOLAGE_CHILDCOUNT,IEP_INCIDENCE_RATE,LUNCH_COUNT_FREE_REDUCED_PCT
0,2000,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,71,69.0,32,...,NaN,5,7.04,*,*,*,*,*,*,NaN
1,2001,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,86,81.0,43,...,NaN,11,12.79,*,*,*,*,*,*,NaN
2,2002,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,92,82.0,35,...,NaN,*,*,*,*,*,*,*,*,NaN
3,2003,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,73,89.0,43,...,NaN,*,*,*,*,*,*,*,*,NaN
4,2004,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,98,98.0,45,...,NaN,5,5.1,*,*,*,*,*,*,NaN
5,2005,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,68,87.0,51,...,NaN,*,*,*,*,*,*,*,*,NaN
6,2000,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,203,426.0,191,...,NaN,171,84.24,*,*,*,*,*,*,NaN
7,2001,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,409,397.0,158,...,NaN,167,40.83,*,*,*,*,*,*,NaN
8,2002,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,428,255.0,128,...,NaN,132,30.84,*,*,*,*,*,*,NaN
9,2003,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,430,322.0,192,...,NaN,108,25.12,*,*,*,*,*,*,NaN
10,2004,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,310,309.0,288,...,NaN,62,20,*,*,*,*,*,*,NaN
11,2005,115115,ST. LOUIS CITY,1100,MILLER CAREER ACADEMY,NaN,,617,603.0,440,...,NaN,57,9.24,*,*,*,*,*,*,NaN
12,2000,115115,ST. LOUIS CITY,1220,GATEWAY HIGH,NaN,,1380,1293.0,708,...,NaN,494,35.8,*,*,*,*,*,*,NaN
13,2001,115115,ST. LOUIS CITY,1220,GATEWAY HIGH,NaN,,1431,1354.0,742,...,NaN,521,36.41,*,*,*,*,*,*,NaN
14,2002,115115,ST. LOUIS CITY,1220,GATEWAY HIGH,NaN,,1485,1395.0,886,...,NaN,547,36.84,*,*,*,*,*,*,NaN
15,2003,115115,ST. LOUIS CITY,1220,GATEWAY HIGH,NaN,,1486,1395.0,917,...,NaN,527,35.46,*,*,*,*,*,*,NaN
16,2004,115115,ST. LOUIS CITY,1220,GATEWAY HIGH,NaN,,1424,1362.0,917,...,NaN,503,35.32,*,*,*,*,*,*,NaN
17,2005,115115,ST. LOUIS CITY,1220,GATEWAY HIGH,NaN,,1340,1267.0,700,...,NaN,447,33.36,*,*,*,*,*,*,NaN
18,2000,115115,ST. LOUIS CITY,1221,GATEWAY MICHAEL HIGH,NaN,,17,16.0,*,...,NaN,*,*,*,*,*,*,*,*,NaN
19,2001,115115,ST. LOUIS CITY,1221,GATEWAY MICHAEL HIGH,NaN,,10,10.0,*,...,NaN,*,*,*,*,*,*,*,*,NaN

In [39]:
stlcity_00_20_sorted = stlcity_00_20.sort_values(by=["SCHOOL_CODE", "COUNTY_DISTRICT_CODE", "YEAR"])

In [40]:
stlcity_00_20_sorted.head(20)

,YEAR,COUNTY_DISTRICT_CODE,DISTRICT_NAME,SCHOOL_CODE,SCHOOL_NAME,TITLE1_FLAG,TITLE1_FLAG_DESC,ENROLLMENT_GRADES_K_12,JANUARY_MEMBERSHIP,LUNCH_COUNT_FREE_REDUCED,...,ENROLLMENT_PACIFIC_ISLANDER_PCT,ENROLLMENT_WHITE,ENROLLMENT_WHITE_PCT,ENROLLMENT_ELL_LEP,ENROLLMENT_ELL_LEP_PCT,ENROLLMENT_GRADE_PK_ELL_LEP,ENROLLMENT_GRADE_PK_ELL_LEP_PCT,IEP_SCHOOLAGE_CHILDCOUNT,IEP_INCIDENCE_RATE,LUNCH_COUNT_FREE_REDUCED_PCT
0,2000,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,71,69.0,32,...,NaN,5,7.04,*,*,*,*,*,*,NaN
1,2001,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,86,81.0,43,...,NaN,11,12.79,*,*,*,*,*,*,NaN
2,2002,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,92,82.0,35,...,NaN,*,*,*,*,*,*,*,*,NaN
3,2003,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,73,89.0,43,...,NaN,*,*,*,*,*,*,*,*,NaN
4,2004,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,98,98.0,45,...,NaN,5,5.1,*,*,*,*,*,*,NaN
5,2005,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,68,87.0,51,...,NaN,*,*,*,*,*,*,*,*,NaN
695,2006,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,69,92.0,53,...,NaN,5,7.25,*,*,*,*,29,42.03,57.6
696,2007,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,69,87.0,33,...,NaN,*,*,*,*,*,*,39,56.52,37.9
697,2008,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,46,23.0,*,...,NaN,*,*,*,*,*,*,7,15.22,*
698,2009,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,23,35.0,12,...,NaN,*,*,*,*,*,*,17,73.91,34.3
699,2010,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,36,52.0,25,...,NaN,*,*,*,*,*,*,*,*,48.1
700,2011,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,43,44.0,29,...,*,*,*,*,*,*,*,14,32.56,65.9
701,2015,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,12,26.0,*,...,*,*,*,*,*,*,*,7,58.33,*
702,2016,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,T,TARGETED,26,29.0,*,...,*,*,*,*,*,*,*,5,19.23,*
703,2017,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,22,30.0,*,...,*,*,*,*,*,*,*,6,27.27,*
704,2018,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,11,21.0,*,...,*,*,*,*,*,*,*,*,*,*
705,2019,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,21,23.0,*,...,*,*,*,*,*,*,*,5,23.81,*
706,2020,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,S,SCHOOLWIDE,11,16.0,*,...,*,*,*,*,*,*,*,*,*,*
707,2007,115115,ST. LOUIS CITY,1020,MADISON ALT. EDUCATION SCH.,NaN,,59,145.0,123,...,NaN,*,*,*,*,*,*,26,44.07,84.8
708,2008,115115,ST. LOUIS CITY,1021,BIG PICTURE ELEM. ALT.,NaN,,58,70.0,60,...,NaN,*,*,*,*,*,*,8,13.79,85.7

In [24]:
school_buildings = pd.read_csv("school_building_list.csv")

In [25]:
school_buildings.head()

,CTYDIST,DNAME,SCHNUM,Textbox285,SCHNAME,SCHADDR1,SCHADDR2,SCHCITY,SCHZIP,SCHLPHON,...,DSUPAREA,HouseDistricts,SenateDistricts,CongressionalDistricts,ELEMENTARY_SCHOOL_FLAG,MIDDLE_SCHOOL_FLAG,JUNIOR_HIGH_SCHOOL_FLAG,HIGH_SCHOOL_FLAG,AVTS_FLAG,ALTERNATIVE_SCHOOL_FLAG
0,115115,St. Louis City,3250,Building List,Acad Of Entre Stdy@louverture,3021 Hickey St.,NaN,St. Louis,631040000,3149321465,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,Y,,,,
1,115115,St. Louis City,4000,Building List,Adams Elem.,1311 Tower Grove Avenue,NaN,St. Louis,631103837,3145353910,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",Y,,,,,
2,115115,St. Louis City,4250,Building List,Ames Visual/Perf. Arts,2900 Hadley,NaN,St. Louis,631073911,3142417165,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",Y,,,,,
3,115115,St. Louis City,4060,Building List,Ashland Elem. and Br.,3921 N Newstead,NaN,St. Louis,631152748,3143854767,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",Y,,,,,
4,115115,St. Louis City,1250,Building List,Beaumont Cte High School,3836 Natural Bridge Avenue,NaN,St. Louis,631072003,3145332410,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,Y,,

In [41]:
stlcity_schools = stlcity_00_20_sorted.merge(school_buildings, left_on=["SCHOOL_CODE", "COUNTY_DISTRICT_CODE"], right_on=["SCHNUM", "CTYDIST"], how="left")

In [42]:
stlcity_schools.head(50)

,YEAR,COUNTY_DISTRICT_CODE,DISTRICT_NAME,SCHOOL_CODE,SCHOOL_NAME,TITLE1_FLAG,TITLE1_FLAG_DESC,ENROLLMENT_GRADES_K_12,JANUARY_MEMBERSHIP,LUNCH_COUNT_FREE_REDUCED,...,DSUPAREA,HouseDistricts,SenateDistricts,CongressionalDistricts,ELEMENTARY_SCHOOL_FLAG,MIDDLE_SCHOOL_FLAG,JUNIOR_HIGH_SCHOOL_FLAG,HIGH_SCHOOL_FLAG,AVTS_FLAG,ALTERNATIVE_SCHOOL_FLAG
0,2000,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,71,69.00,32,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
1,2001,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,86,81.00,43,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
2,2002,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,92,82.00,35,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
3,2003,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,73,89.00,43,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
4,2004,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,98,98.00,45,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
5,2005,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,68,87.00,51,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
6,2006,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,69,92.00,53,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
7,2007,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,69,87.00,33,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
8,2008,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,46,23.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
9,2009,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,23,35.00,12,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
10,2010,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,36,52.00,25,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
11,2011,115115,ST. LOUIS CITY,1015,GRISCOM DETENTION CTR.,NaN,,43,44.00,29,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
12,2015,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,12,26.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
13,2016,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,T,TARGETED,26,29.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
14,2017,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,22,30.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
15,2018,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,11,21.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
16,2019,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,NaN,,21,23.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
17,2020,115115,ST. LOUIS CITY,1015,GRISCOM JUVENILE DETENTION CTR,S,SCHOOLWIDE,11,16.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,,Y
18,2007,115115,ST. LOUIS CITY,1020,MADISON ALT. EDUCATION SCH.,NaN,,59,145.00,123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2008,115115,ST. LOUIS CITY,1021,BIG PICTURE ELEM. ALT.,NaN,,58,70.00,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2009,115115,ST. LOUIS CITY,1021,BIG PICTURE ELEM. ALT.,NaN,,63,62.00,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2008,115115,ST. LOUIS CITY,1022,BIG PICTURE MIDDLE ALT.,NaN,,60,58.00,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2009,115115,ST. LOUIS CITY,1022,BIG PICTURE MIDDLE ALT.,NaN,,64,67.00,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2008,115115,ST. LOUIS CITY,1023,BIG PICTURE HIGH SCHOOL ALT.,NaN,,65,58.00,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2009,115115,ST. LOUIS CITY,1023,BIG PICTURE HIGH SCHOOL ALT.,NaN,,85,90.00,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2010,115115,ST. LOUIS CITY,1023,BIG PICTURE MIDDLE & HIGH @ NW,NaN,,139,124.00,112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2011,115115,ST. LOUIS CITY,1023,BIG PICTURE MIDDLE & HIGH @ NW,S,SCHOOLWIDE,121,113.00,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2016,115115,ST. LOUIS CITY,1024,EDUC THERAP SUPPORT AT MADISON,NaN,,0,0.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,Y,,
28,2017,115115,ST. LOUIS CITY,1024,EDUC THERAP SUPPORT AT MADISON,NaN,,0,0.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,Y,,
29,2018,115115,ST. LOUIS CITY,1024,EDUC THERAP SUPPORT AT MADISON,NaN,,0,0.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,Y,,
30,2019,115115,ST. LOUIS CITY,1024,EDUC THERAP SUPPORT AT MADISON,NaN,,0,0.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,Y,,
31,2020,115115,ST. LOUIS CITY,1024,EDUC THERAP SUPPORT AT MADISON,NaN,,0,0.00,*,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,Y,,
32,2006,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,26,28.00,*,...,A,NaN,NaN,NaN,,,,Y,,
33,2007,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,20,19.00,*,...,A,NaN,NaN,NaN,,,,Y,,
34,2008,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,21,19.00,*,...,A,NaN,NaN,NaN,,,,Y,,
35,2009,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,22,19.37,6.4,...,A,NaN,NaN,NaN,,,,Y,,
36,2010,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,25,19.47,10,...,A,NaN,NaN,NaN,,,,Y,,
37,2011,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,29,27.89,*,...,A,NaN,NaN,NaN,,,,Y,,
38,2012,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,25,22.65,*,...,A,NaN,NaN,NaN,,,,Y,,
39,2013,115414,MO SCHOOL FOR THE BLIND,1050,MSB HIGH,NaN,,27,28.00,*,...,A,NaN,NaN,NaN,,,,Y,,
40,2014,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,29,28.00,*,...,A,NaN,NaN,NaN,,,,Y,,
41,2015,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,27,26.00,*,...,A,NaN,NaN,NaN,,,,Y,,
42,2016,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,29,26.00,*,...,A,NaN,NaN,NaN,,,,Y,,
43,2017,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,22,22.00,*,...,A,NaN,NaN,NaN,,,,Y,,
44,2018,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,27,24.00,*,...,A,NaN,NaN,NaN,,,,Y,,
45,2019,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,24,24.00,*,...,A,NaN,NaN,NaN,,,,Y,,
46,2020,115414,MO SCHOOL FOR THE BLIND,1050,MO School for the Blind - HS,NaN,,25,26.00,*,...,A,NaN,NaN,NaN,,,,Y,,
47,2000,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,203,426.00,191,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,Y,
48,2001,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,409,397.00,158,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,Y,
49,2002,115115,ST. LOUIS CITY,1100,CAREER ACADEMY,NaN,,428,255.00,128,...,A,"66 , 76 , 77 , 78 , 79 , 80 , 81 , 82 , 83 , 8...","4 , 5","01, 02",,,,,Y,

In [43]:
stlcity_schools.to_csv("stl_city_schools.csv")

In [44]:
%pip install PyPDF2

Collecting PyPDF2
  Downloading PyPDF2-1.26.0.tar.gz (77 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 77 kB 4.5 MB/s eta 0:00:011
Building wheels for collected packages: PyPDF2
  Building wheel for PyPDF2 (setup.py) ... done
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61085 sha256=d9ea534fecc98b12e795b16765d4d901afde6ed33b4f5155b775a6991c699661
  Stored in directory: /Users/davidhackett/Library/Caches/pip/wheels/d9/dc/ec/72da68331f30074b9950c1737c23cb8a67484e61498bc9713d
Successfully built PyPDF2
Installing collected packages: PyPDF2
Successfully installed PyPDF2-1.26.0
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/3.0.16_1/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [46]:
import PyPDF2 as pypdf
reader = pypdf.PdfFileReader("charter_schools_directory.pdf")

In [49]:
charter_codes = []
number_of_pages = reader.getNumPages()

In [59]:
for page_num in range(1, number_of_pages - 1):
    text = reader.getPage(page_num).extractText()
    arr = text.replace("\n", "").split(" ")
    try:
        idx = arr.index('Code:')
        code = arr[idx + 1]
        charter_codes.append(code)
    except:
        continue

In [60]:
print(charter_codes)

['115-911-6955', '115-906', '115-906-1920', '115-906-1945', '115-906-3920', '115-906-6931', '115-906-6930', '115-906-6932', '115-923', '115-923-6996', '115-923-6998', '115-923-6997', '115-923-6995', '115-916', '115-916-1940', '115-916-3935', '115-916-6980', '115-916-6997', '115-925-1905', '115-925-3910', '115-931-3945', '115-914', '115-914-1905', '115-914-6970', '115-914-6973', '115-914-6971', '115-914-6972', '115-914-6974', '115-928-3910', '115-924-6993', '115-902', '115-902-1935', '115-902-3910', '115-902-6905', '115-913', '115-913-6970', '115-913-6965', '115-903-6915', '115-912-6961', '115-930-6905', '115-926-6905']

In [78]:
def create_full_code(row):
    district_str = str(row["COUNTY_DISTRICT_CODE"])
    return district_str[:3] + "-" + district_str[3:] + "-" + str(row["SCHOOL_CODE"]) 
    

stlcity_schools["FULL_CODE"] = stlcity_schools.apply(create_full_code, axis=1)

In [79]:
stlcity_schools["FULL_CODE"]

0       115-115-1015
1       115-115-1015
2       115-115-1015
3       115-115-1015
4       115-115-1015
            ...
2312    115-115-9995
2313    115-115-9995
2314    115-115-9995
2315    115-115-9995
2316    115-115-9995
Name: FULL_CODE, Length: 2317, dtype: object

In [81]:
def in_charter(value):
    return value in charter_codes
stlcity_schools["CHARTER"] = stlcity_schools["FULL_CODE"].apply(in_charter)

In [83]:
charter_schools = stlcity_schools[stlcity_schools["CHARTER"]]

In [85]:
charter_schools.shape

(237, 71)